### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by glemaitre** [paris-saclay-cds/ramp-autism-website#5]
To finalize the website, we need:

- [x] Location.
- [x] Agree on the date
- [x] Check the description of the data
- [ ] Contact the brainhack organization

**Comment by glemaitre** [comment]
@GaelVaroquaux Can you make a review of the changes

**Comment by GaelVaroquaux** [comment]
>   • [ ] Agree on the date

We need to contact Pasteur for this. Also, we should chat, with Balazs,
on the details of the organization.

**Comment by glemaitre** [comment]
@GaelVaroquaux Shall we contact people from the brainhack?
